#!/usr/bin/env python
"""
   Copyright 2009, Patrick Shields

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

import sys
import argloop
from nws.client import NetWorkSpace

validOptions = {'n':'localhost', 'p':'8765', 'w':'__default'}

helpMessage = """
Usage: delete [options] variable | workspace
Delete a NetWorkSpace variable or workspace. 
Defaults to deleting the default workspace.

Options:
-n  Hostname to connect to the server on. Defaults to 'localhost'.
-p  Port to connect to ther server on. Defaults to '8765'.
-w  Workspace to use in variable deletion. Defaults to '__default'.
    Not used when deleting a workspace.

example:
delete -nmysystem -p2222 myspace
or
delete -nmysystem -p2222 -wfoospace myvar
"""

def delete(workspace = None, variable = None):
   if variable != None:
      workspace.deleteVar(variable)
   else:
      workspace.server.deleteWs(workspace.curWs)      

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: delete [options] workspace | variable\nUse -h for help\n')
        sys.exit(1)
    options = argloop.processArgs(sys.argv[1:])
    
    if len(options) > 0 and options[0] == '-h':
        print helpMessage
        sys.exit(0)

    for opt in options:
        if validOptions.keys().count(opt[1]) < 1:
            sys.stderr.write('Invalid option: '+opt[:2]+'\n')
            sys.exit(1)
        if len(opt) == 2:
            validOptions[opt[1]] = True
        else:
            validOptions[opt[1]] = opt[2:]
    
    workspace = NetWorkSpace(wsName = validOptions['w'], serverHost = validOptions['n'],
                             serverPort = int(validOptions['p']))

    if len(options) + 1 == len(sys.argv):
       delete(workspace)
    else:
       delete(workspace, sys.argv[len(sys.argv)-1])
