#!/usr/bin/env python

import sys
from nws.client import NetWorkSpace

def fetch(val):
    ws = NetWorkSpace(sys.argv[1])
    sys.stdout.write(ws.fetch(val)+'\n')

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: store workspace variable value\n')
        sys.exit(1)
    elif len(sys.argv) == 2:
        for value in sys.stdin:
            fetch(value)
    elif len(sys.argv) == 3:
        fetch(sys.argv[2])
    else:
        sys.stderr.write("I just don't understand")

