#!/usr/bin/env python

import sys
import argloop
from nws.client import NetWorkSpace

validOptions = {'t':False, 'n':'localhost', 'p':'8765', 'w':'__default', 'v':'default', 'r':False}

helpMessage = """
Usage: fetch [options] [variable]
Fetch a NetWorkSpace variable value.  stdin variables accepted.

Options:
-t  Try. Do not block if no values are availible. Off by default.
-n  Hostname to connect to the server on. Defaults to 'localhost'.
-p  Port to connect to ther server on. Defaults to '8765'.
-w  Workspace name to use. Defaults to '__default'.
-r  read from stdin. Will ignore any variable passed.
    Off by default.

Variable name defaults to 'default'.

example:
fetch -t -nmysystem -p2222 -wfood eggs
or
cat breakfast_foods.txt | fetch -t -r -nmysystem -p2222 -wfood
"""

def fetch(workspace, variable, tri=False):
    if tri:
        ret = workspace.fetchTry(variable)
        if ret == None:
            ret = ''
        sys.stdout.write(ret+'\n')
    else:
        sys.stdout.write(workspace.fetch(variable)+'\n')

if __name__ == '__main__':
    options = argloop.processArgs(sys.argv[1:])
    
    if len(options) > 0 and options[0] == '-h':
        print helpMessage
        sys.exit(0)

    for opt in options:
        if validOptions.keys().count(opt[1]) < 1:
            sys.stderr.write('Invalid option: '+opt[:2]+'\n')
            sys.exit(1)
        if len(opt) == 2:
            validOptions[opt[1]] = True
        else:
            validOptions[opt[1]] = opt[2:]
    
    workspace = NetWorkSpace(wsName = validOptions['w'], serverHost = validOptions['n'],
                             serverPort = int(validOptions['p']))

    if validOptions['r']:
        for value in sys.stdin:
            fetch(workspace, value.strip(), validOptions['t'])
    else:
        fetch(workspace, sys.argv[len(sys.argv)-1], validOptions['t'])
