#!/usr/bin/env python

import sys
from nws.client import NetWorkSpace

def find(val):
    ws = NetWorkSpace(sys.argv[1])
    sys.stdout.write(ws.find(val)+'\n')

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: find workspace variable\n')
        sys.exit(1)
    elif len(sys.argv) == 2:
        for value in sys.stdin:
            find(value)
    elif len(sys.argv) == 3:
        find(sys.argv[2])
    else:
        sys.stderr.write("I just don't understand")

