#!/usr/bin/env python
"""
   Copyright 2009, Patrick Shields

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

import sys
import argloop
from nws.client import NetWorkSpace

validOptions = {'n':'localhost', 'p':'8765', 'w':'__default', 'v':'default'}

helpMessage = """
Usage: store [options] value
Store a NetWorkSpace variable value.  stdin values accepted.

Options:
-n  Hostname to connect to the server on. Defaults to 'localhost'.
-p  Port to connect to ther server on. Defaults to '8765'.
-w  Workspace name to use. Defaults to '__default'.
-v  Variable name to use. Defaults to 'default'.

example:
store -nmysystem -p2222 -wfood -vbreakfast eggs
or
cat breakfast_foods.txt | store -nmysystem -p2222 -wfood -vbreakfast
"""

def store(workspace, variable, value):
    workspace.store(variable, value)

if __name__ == '__main__':
    options = argloop.processArgs(sys.argv[1:])
    
    if len(options) > 0 and options[0] == '-h':
        print helpMessage
        sys.exit(0)

    for opt in options:
        if validOptions.keys().count(opt[1]) < 1:
            sys.stderr.write('Invalid option: '+opt[:2]+'\n')
            sys.exit(1)
        if len(opt) == 2:
            validOptions[opt[1]] = True
        else:
            validOptions[opt[1]] = opt[2:]
    
    workspace = NetWorkSpace(wsName = validOptions['w'], serverHost = validOptions['n'],
                             serverPort = int(validOptions['p']), persistent = True)

    if len(options) + 1 == len(sys.argv):
        for value in sys.stdin:
            store(workspace, validOptions['v'], value)
    else:
        store(workspace, validOptions['v'], sys.argv[len(sys.argv)-1])
